# ============================================
# SECRET - Datos SENSIBLES
# ============================================
apiVersion: v1
kind: Secret
metadata:
  name: order-service-secret
  namespace: order-service
  labels:
    app: order-service

type: Opaque

# stringData convierte automáticamente a base64
stringData:
  DB_USERNAME: "postgres"
  DB_PASSWORD: "postgres"