apiVersion: v1
kind: Service
metadata:
  name: zipkin
  namespace: observability
  labels:
    app: zipkin

spec:
  type: NodePort

  selector:
    app: zipkin

  ports:
    - name: http
      port: 9411
      targetPort: 9411
      nodePort: 30411