# ============================================
# SECRET - Datos SENSIBLES
# ============================================
apiVersion: v1
kind: Secret
metadata:
  name: payment-service-secret
  namespace: payment-service
  labels:
    app: payment-service

type: Opaque

# stringData convierte automáticamente a base64
stringData:
  DB_USERNAME: "postgres"
  DB_PASSWORD: "postgres"