# ============================================
# CONFIGMAP - Configuración NO sensible
# ============================================
apiVersion: v1
kind: ConfigMap
metadata:
  name: delivery-service-config
  namespace: delivery-service
  labels:
    app: delivery-service

# Pares clave-valor
data:

  # ⭐ CLAVE: Usa el nombre del Service de user-service
  ##USER_SERVICE_URL: "http://user-service"
  #USER_SERVICE_URL: "http://user-service.user-service.svc.cluster.local"
  USER_SERVICE_URL: "http://user-service.user-service.svc.cluster.local:80"

  PRODUCT_SERVICE_URL: "http://product-service.product-service.svc.cluster.local:80"

  ORDER_SERVICE_URL: "http://order-service.order-service.svc.cluster.local:80"

  KAFKA_BOOTSTRAP_SERVERS: "kafka.kafka.svc.cluster.local:9092"
  # URL de la base de datos
  # host.docker.internal apunta a localhost de tu PC
  DB_URL: "jdbc:postgresql://host.docker.internal:5442/deliverydb"


  # Configuración de JPA
  DDL_AUTO: "validate"
  SHOW_SQL: "false"

  # Pool de conexiones
  POOL_SIZE: "10"

  # Logging
  LOG_LEVEL: "INFO"
  SQL_LOG_LEVEL: "WARN"

  # JVM
  JAVA_OPTS: "-Xmx512m -Xms256m"