# ============================================
# SECRET - Datos SENSIBLES
# ============================================
apiVersion: v1
kind: Secret
metadata:
  name: delivery-service-secret
  namespace: delivery-service
  labels:
    app: delivery-service

type: Opaque

# stringData convierte automáticamente a base64
stringData:
  DB_USERNAME: "postgres"
  DB_PASSWORD: "postgres"